# Generated by Django 5.2.1 on 2025-06-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0005_alter_campanha_id_alter_contato_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamentos',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
